name: flutter_morozteam_ui
description: Universal UI kit for Flutter applications with flexible configuration system for colors, typography and spacing
version: 0.1.0
homepage: https://github.com/MorozTeam/flutter_morozteam_ui
repository: https://github.com/MorozTeam/flutter_morozteam_ui
issue_tracker: https://github.com/MorozTeam/flutter_morozteam_ui/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
