name: morozteam_ui
description: Universal UI kit for Flutter applications with flexible configuration system for colors, typography and spacing
version: 0.2.0
homepage: https://github.com/MorozTeam/flutter_morozteam_ui
repository: https://github.com/MorozTeam/flutter_morozteam_ui
issue_tracker: https://github.com/MorozTeam/flutter_morozteam_ui/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  crypto: any
  flutter:
    sdk: flutter
  flutter_svg: any
  webview_flutter: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
