name: morozteam_ui
description: Universal UI kit for Flutter applications with flexible configuration system for colors, typography and spacing
version: 0.2.0
homepage: https://github.com/MorozTeam/flutter_morozteam_ui
repository: https://github.com/MorozTeam/flutter_morozteam_ui
issue_tracker: https://github.com/MorozTeam/flutter_morozteam_ui/issues
license: MIT

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
